const collection  = [
    {title: "Social life jazz", img: "/photo-1.avif"},
    {title: "Music with friends", img: "/photo-2.avif"},
    {title: "Radio jazz", img: "/photo-3.avif"},
    {title: "Jazz in the city", img: "/photo-4.avif"},
    {title: "Model jazzzz~", img: "/photo-5.jpg"},
    {title: "Smile ",img: "/photo-6.jpg"},
    {title: "Statue with the jazz touch", img: "/photo-7.jpg"},
    {title: "Let your soul dance", img: "/photo-8.jpg"},
    {title: "Jazz Club", img: "/photo-9.avif"},
    {title: "Singer", img: "/photo-10.avif"},
    {title: "Saxophone", img: "/photo-11.avif"},
    {title: "Books and jazz", img: "/photo-12.avif"},
    {title: "lost yourself with books", img: "/photo-13.avif"},
    {title: "Start and end with the books", img: "/photo-14.avif"},
    {title: "Purple world", img: "/photo-15.avif"},
    {title: "Weather is everything", img: "/photo-16.avif"},
    {title: "Get up in the morning", img: "/photo-17.avif"},
    {title: "Bird in the sky", img: "/photo-18.avif"},
    {title: "when the white and jazzz together", img: "/photo-19.avif"},
    {title: "For the Love of White", img: "/photo-20.avif"},
];
export default collection;